Getting Statred With Pandas

In [10]:
#Pandas Series (1D)

import pandas as pd 

ser=pd.Series([1,2,3,4,5],name="number")
ser


#Pandas DataFrame(2D)

df=pd.DataFrame({
    "Name":["nam1","nam2","nam3","nam4","nam5"],
    "Age" :[14,16,18,25,23]
})
df  #use Print or just call var to Print the output result

   Name  Age
0  nam1   14
1  nam2   16
2  nam3   18
3  nam4   25
4  nam5   23

LOAD DATA FROM A DATASET

In [12]:
#Import Necessary Libraries

import numpy as pnp
import pandas as pd

#Load a DataSet
studentdf= pd.read_csv("StudentPerformanceFactors.csv")
studentdf

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [30]:
#Read the DataSet and Find about it..


studentdf.info() #Gives Entire Row
print("-------------------------------------------------------------------------------")
display(studentdf.describe()) #Statistical Data
print("-------------------------------------------------------------------------------")
#To Display first and Last Five Rows

print("First 5 Rows:")
display(studentdf.head(5))

print("Last 5 Rows:")
display(studentdf.tail(5))

display("Size:",studentdf.shape)
display("Columns",studentdf.columns)
display("Type",studentdf.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB
-------------------------------------------------------------------------------

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

-------------------------------------------------------------------------------
First 5 Rows:

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

Last 5 Rows:

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

'Size:'

(6607, 20)

'Columns'

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

'Type'

Hours_Studied                  int64
Attendance                     int64
Parental_Involvement          object
Access_to_Resources           object
Extracurricular_Activities    object
Sleep_Hours                    int64
Previous_Scores                int64
Motivation_Level              object
Internet_Access               object
Tutoring_Sessions              int64
Family_Income                 object
Teacher_Quality               object
School_Type                   object
Peer_Influence                object
Physical_Activity              int64
Learning_Disabilities         object
Parental_Education_Level      object
Distance_from_Home            object
Gender                        object
Exam_Score                     int64
dtype: object

ETL-ExTRACT,TRANSFORM and LOAD

In [40]:
#Data Quality Check 

#Find missing Values
print("Null Values:")
display(studentdf.isnull().sum()) #To find missing values

print("Duplicate Rows:", studentdf.duplicated().sum())

#Find Attendence greater than 100 or not
print("Check for Attendance ")
display(studentdf['Attendance'].max())

print("Check for Negitive values:")
display(studentdf['Sleep_Hours'].min())

Null Values:

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

Duplicate Rows: 0
Check for Attendance

100

Check for Negitive values:

4

Data Cleaning and Transformation

In [52]:

# 1. Remove Unwanted Columns

studentdf.drop(
    columns=[
        'Teacher_Quality',
        'Parental_Education_Level',
        'Distance_from_Home'
    ],
    inplace=True
)

print("Columns after removing unwanted columns:")
display(studentdf.head())


# 2. Handle Missing Values


print("Missing Values Before Handling:")
display(studentdf.isnull().sum())


# Fill numerical columns with median
numeric_columns = studentdf.select_dtypes(include='number').columns

for column in numeric_columns:
    studentdf[column] = studentdf[column].fillna(
        studentdf[column].median()
    )


# Fill categorical columns with mode
categorical_columns = studentdf.select_dtypes(include='object').columns

for column in categorical_columns:
    studentdf[column] = studentdf[column].fillna(
        studentdf[column].mode()[0]
    )


print("Missing Values After Handling:")
display(studentdf.isnull().sum())



# 3. Remove Duplicate Rows


print("Duplicate Rows Before Removing:",
      studentdf.duplicated().sum())

studentdf.drop_duplicates(inplace=True)

print("Duplicate Rows After Removing:",
      studentdf.duplicated().sum())



# 4. Check Data Types


print("Data Types:")
display(studentdf.dtypes)


# 5. Check Categorical Values


print("Gender Values:")
display(studentdf['Gender'].value_counts())

print("Parental Involvement Values:")
display(studentdf['Parental_Involvement'].value_counts())

print("Motivation Level Values:")
display(studentdf['Motivation_Level'].value_counts())

print("Family Income Values:")
display(studentdf['Family_Income'].value_counts())

print("School Type Values:")
display(studentdf['School_Type'].value_counts())



# 6. Check Invalid Values


print("Attendance Greater Than 100:")
display(studentdf[studentdf['Attendance'] > 100])

print("Negative Hours Studied:")
display(studentdf[studentdf['Hours_Studied'] < 0])

print("Negative Sleep Hours:")
display(studentdf[studentdf['Sleep_Hours'] < 0])

print("Invalid Previous Scores:")
display(
    studentdf[
        (studentdf['Previous_Scores'] < 0) |
        (studentdf['Previous_Scores'] > 100)
    ]
)

print("Invalid Exam Scores:")
display(
    studentdf[
        (studentdf['Exam_Score'] < 0) |
        (studentdf['Exam_Score'] > 100)
    ]
)



# 9. Final Data Validation


print("\n========== FINAL DATA VALIDATION ==========")

print("Dataset Shape:")
print(studentdf.shape)

print("\nMissing Values:")
display(studentdf.isnull().sum())

print("Total Missing Values:",
      studentdf.isnull().sum().sum())

print("\nDuplicate Rows:")
print(studentdf.duplicated().sum())

print("\nData Types:")
display(studentdf.dtypes)

print("\nFirst 10 Rows:")
display(studentdf.head(10))

In [54]:
# Transform Creating new Features

studentdf['Performance_Category'] = pd.cut(
    studentdf['Exam_Score'],
    bins=[0, 40, 70, 100],
    labels=['Low', 'Medium', 'High']
)

studentdf.head(10)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Gender,Exam_Score,Study_Category,Performance_Category
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Public,Positive,3,No,Male,67,High,Medium
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Public,Negative,4,No,Female,61,High,Medium
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Public,Neutral,4,No,Male,74,High,High
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Public,Negative,4,No,Male,71,High,High
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,Public,Neutral,4,No,Female,70,High,Medium
5,19,88,Medium,Medium,Yes,8,89,Medium,Yes,3,Medium,Public,Positive,3,No,Male,71,High,High
6,29,84,Medium,Low,Yes,7,68,Low,Yes,1,Low,Private,Neutral,2,No,Male,67,High,Medium
7,25,78,Low,High,Yes,6,50,Medium,Yes,1,High,Public,Negative,2,No,Male,66,High,Medium
8,17,94,Medium,High,No,6,80,High,Yes,0,Medium,Private,Neutral,1,No,Male,69,High,Medium
9,23,98,Medium,Medium,Yes,8,71,Medium,Yes,0,High,Public,Positive,5,No,Male,72,High,High

In [58]:
#Analysis 

Student_Performance = studentdf[
    [
        'Hours_Studied',
        'Attendance',
        'Sleep_Hours',
        'Previous_Scores',
        'Tutoring_Sessions',
        'Exam_Score',
        'Study_Category',
        'Performance_Category'
    ]
]

Student_Performance

# 1. SUM
print("Total Hours Studied:")
print(Student_Performance['Hours_Studied'].sum())

print("\nTotal Tutoring Sessions:")
print(Student_Performance['Tutoring_Sessions'].sum())



# 2. MEAN


print("\nAverage Hours Studied:")
print(Student_Performance['Hours_Studied'].mean())

print("\nAverage Attendance:")
print(Student_Performance['Attendance'].mean())

print("\nAverage Exam Score:")
print(Student_Performance['Exam_Score'].mean())


# 3. MEDIAN


print("\nMedian Hours Studied:")
print(Student_Performance['Hours_Studied'].median())

print("\nMedian Exam Score:")
print(Student_Performance['Exam_Score'].median())


# 4. MIN

print("\nMinimum Hours Studied:")
print(Student_Performance['Hours_Studied'].min())

print("\nMinimum Attendance:")
print(Student_Performance['Attendance'].min())

print("\nMinimum Exam Score:")
print(Student_Performance['Exam_Score'].min())


# 5. MAX

print("\nMaximum Hours Studied:")
print(Student_Performance['Hours_Studied'].max())

print("\nMaximum Attendance:")
print(Student_Performance['Attendance'].max())

print("\nMaximum Exam Score:")
print(Student_Performance['Exam_Score'].max())


# 6. COUNT


print("\nNumber of Exam Scores:")
print(Student_Performance['Exam_Score'].count())

print("\nNumber of Attendance Values:")
print(Student_Performance['Attendance'].count())

#7. SIZE


print("\nTotal Number of Rows:")
print(Student_Performance.size)



# 8. STANDARD DEVIATION


print("\nStandard Deviation of Exam Score:")
print(Student_Performance['Exam_Score'].std())

print("\nStandard Deviation of Attendance:")
print(Student_Performance['Attendance'].std())


# 9. VARIANCE


print("\nVariance of Exam Score:")
print(Student_Performance['Exam_Score'].var())

print("\nVariance of Attendance:")
print(Student_Performance['Attendance'].var())



# 10. UNIQUE


print("\nUnique Study Categories:")
print(Student_Performance['Study_Category'].unique())

print("\nUnique Performance Categories:")
print(Student_Performance['Performance_Category'].unique())



# 11. NUNIQUE


print("\nNumber of Study Categories:")
print(Student_Performance['Study_Category'].nunique())

print("\nNumber of Performance Categories:")
print(Student_Performance['Performance_Category'].nunique())



# 12. AGG


print("\nMultiple Aggregations on Exam Score:")

display(
    Student_Performance['Exam_Score'].agg(
        ['sum', 'mean', 'median', 'min', 'max', 'count', 'std', 'var']
    )
)



# 13. AGG ON MULTIPLE COLUMNS


print("\nMultiple Aggregations on Multiple Columns:")

display(
    Student_Performance.agg({
        'Hours_Studied': ['mean', 'min', 'max'],
        'Attendance': ['mean', 'min', 'max'],
        'Exam_Score': ['mean', 'median', 'min', 'max'],
        'Tutoring_Sessions': ['sum', 'mean', 'max']
    })
)

Total Hours Studied:
131977

Total Tutoring Sessions:
9869

Average Hours Studied:
19.975329196306948

Average Attendance:
79.97744816104132

Average Exam Score:
67.23565914938702

Median Hours Studied:
20.0

Median Exam Score:
67.0

Minimum Hours Studied:
1

Minimum Attendance:
60

Minimum Exam Score:
55

Maximum Hours Studied:
44

Maximum Attendance:
100

Maximum Exam Score:
101

Number of Exam Scores:
6607

Number of Attendance Values:
6607

Total Number of Rows:
52856

Standard Deviation of Exam Score:
3.890455781261724

Standard Deviation of Attendance:
11.547474961482802

Variance of Exam Score:
15.135646185952773

Variance of Attendance:
133.34417798607222

Unique Study Categories:
['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

Unique Performance Categories:
['Medium', 'High', NaN]
Categories (3, object): ['Low' < 'Medium' < 'High']

Number of Study Categories:
3

Number of Performance Categories:
2

Multiple Aggregations on Exam Score:

sum       444226.000000
mean          67.235659
median        67.000000
min           55.000000
max          101.000000
count       6607.000000
std            3.890456
var           15.135646
Name: Exam_Score, dtype: float64

Multiple Aggregations on Multiple Columns:

        Hours_Studied  Attendance  Exam_Score  Tutoring_Sessions
mean        19.975329   79.977448   67.235659           1.493719
min          1.000000   60.000000   55.000000                NaN
max         44.000000  100.000000  101.000000           8.000000
median            NaN         NaN   67.000000                NaN
sum               NaN         NaN         NaN        9869.000000

In [59]:
#Group BY

Student_Performance.groupby('Study_Category')['Exam_Score'].mean()

C:\Users\jithu\AppData\Local\Temp\ipykernel_23120\1987517089.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  Student_Performance.groupby('Study_Category')['Exam_Score'].mean()

Study_Category
Low       65.666667
Medium    62.080000
High      67.277184
Name: Exam_Score, dtype: float64

In [60]:
#Load

Student_Performance.to_csv(
    'Student_Performance_Cleaned.csv',
    index=False
)